version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: cartlify_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cartlify
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: cartlify_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cartlify.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data: